import Container from './component/Container'
import './globals.css'
import DarkMode from './DarkMode'
import {cookies} from 'next/headers';


export const metadata = {
  title: 'TODO APP',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {

  let cookie = cookies().get('mode')
  console.log(cookie)

  return (
    <html lang="en">
      <body className={
        cookie != undefined && cookie.value == 'dark' 
        ? 'dark-mode' 
        : ''}>
        <DarkMode/>
        <Container children={children} />
      </body>
    </html>
  )
}
